### ISSUE TITLE
Can't show graphic with web command in go tool pprof  

### ISSUE THREAD

**Issue by marknewmail** [echo-contrib/echopprof#4]
if you use pprof like go tool pprof  -seconds 15 http://localhost:8080/debug/pprof/profile
and use "web" command ,will raise follow errors in service like this,
{"time":"2016-08-06T17:35:16+08:00","level":"ERROR","prefix":"echo","file":"echo.go","line":"230","message":"Method Not Allowed"}
and graphic is empty

**Comment by insionng** [comment]
Can u try gif mode?
